### ISSUE TITLE
Possible to chroot users into their homes

### ISSUE THREAD

**Issue by laubed** [couling/WebDAV-Daemon#2]
Is it possible to chroot users to their home directories?

**Comment by couling** [comment]
The code doesn't currently support this.  Although I really like the idea.

- Configuration to enable / specify path.  It's insufficient to assume this may only be used for a user's home directory.
- Identification of the user's home directory
- Add a [chroot](https://linux.die.net/man/2/chroot) to the configured / home directory.  This would be done on [line 261 of shared.c](https://github.com/couling/WebDAV-Daemon/blob/73d5d2c83fb8c50bd53d819c170880c6f6d54894/shared.c#L261)

It may take me a while to get to this. If you wanted to brave building the code yourself, then you could change the above line of code to this:

```
if (initgroups(user, pwd->pw_gid) || setgid(pwd->pw_gid) || chroot(pwd->pw_dir) || setuid(pwd->pw_uid)) {
```

**Comment by laubed** [comment]
I made some experiments with the source on my own. If i remember correctly the result was that when i had a working working chroot some files could not be read by the server because they were outside the chroot (server files/configuration, not user files).
I will test that new branch soon to see if the server now meets our requirements.

Thank you

**Comment by couling** [comment]
Yes, the server is in two parts.  The core server, and a worker "`rap`".  The code I mentioned above failed initially because both the core server and the worker execute the same piece of code.  To make this work correctly, only the worker should `chroot`.  I forgot to mention, to test the new code, makesure the config file contains `<chroot-path>~</chroot-path>` so that the worker locks down to the user's home directory.

**Comment by couling** [comment]
I think this is now all fixed and working (enabled by default).  Give me a shout if you have problems.
